spring.application.name=backPayments
spring.cloud.compatibility-verifier.enabled=false
spring.autoconfigure.exclude=org.springframework.cloud.client.discovery.simple.SimpleDiscoveryClientAutoConfiguration,org.springframework.cloud.autoconfigure.RefreshAutoConfiguration,org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration
spring.sql.init.mode=always
spring.sql.init.platform=${APP_DB_PLATFORM:h2}
spring.sql.init.separator=@@
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

logging.level.root=${APP_LOG_LEVEL_ROOT:INFO}
logging.level.com.assesment.backpayments=${APP_LOG_LEVEL_APP:DEBUG}
logging.level.org.springframework.security=${APP_LOG_LEVEL_SECURITY:DEBUG}
logging.level.org.hibernate.SQL=${APP_LOG_LEVEL_HIBERNATE_SQL:DEBUG}
logging.level.org.hibernate.orm.jdbc.bind=${APP_LOG_LEVEL_HIBERNATE_BIND:TRACE}

app.security.jwt.secret=${APP_SECURITY_JWT_SECRET:password}
app.security.jwt.expiration=PT2H

app.storage.provider=${APP_STORAGE_PROVIDER:local}
app.storage.invoice-root=${APP_STORAGE_INVOICE_ROOT:./data/invoices}

app.integration.dummy-url=${APP_INTEGRATION_DUMMY_URL:https://postman-echo.com}
app.integration.provider-name=${APP_INTEGRATION_PROVIDER_NAME:postman-echo}
app.integration.persist-response=${APP_INTEGRATION_PERSIST_RESPONSE:true}
app.integration.connect-timeout=${APP_INTEGRATION_CONNECT_TIMEOUT:2s}
app.integration.read-timeout=${APP_INTEGRATION_READ_TIMEOUT:5s}

resilience4j.retry.instances.dummyIntegration.max-attempts=3
resilience4j.retry.instances.dummyIntegration.wait-duration=500ms
resilience4j.circuitbreaker.instances.dummyIntegration.sliding-window-size=5
resilience4j.circuitbreaker.instances.dummyIntegration.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.dummyIntegration.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.dummyIntegration.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.dummyIntegration.wait-duration-in-open-state=20s

app.seed.enabled=${APP_SEED_ENABLED:true}
app.seed.admin.email=${APP_SEED_ADMIN_EMAIL:admin@local}
app.seed.admin.password=${APP_SEED_ADMIN_PASSWORD:Admin123!}
app.seed.operator.email=${APP_SEED_OPERATOR_EMAIL:operator@local}
app.seed.operator.password=${APP_SEED_OPERATOR_PASSWORD:Operator123!}
