spring.application.name=backPayments
spring.cloud.compatibility-verifier.enabled=false
spring.autoconfigure.exclude=org.springframework.cloud.client.discovery.simple.SimpleDiscoveryClientAutoConfiguration,org.springframework.cloud.autoconfigure.RefreshAutoConfiguration,org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration

app.security.jwt.secret=password
app.security.jwt.expiration=PT2H

app.storage.provider=local
app.storage.invoice-root=./data/invoices

app.integration.dummy-url=https://postman-echo.com
app.integration.provider-name=postman-echo
app.integration.persist-response=true
app.integration.connect-timeout=2s
app.integration.read-timeout=5s

resilience4j.retry.instances.dummyIntegration.max-attempts=3
resilience4j.retry.instances.dummyIntegration.wait-duration=500ms
resilience4j.circuitbreaker.instances.dummyIntegration.sliding-window-size=5
resilience4j.circuitbreaker.instances.dummyIntegration.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.dummyIntegration.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.dummyIntegration.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.dummyIntegration.wait-duration-in-open-state=20s

app.seed.enabled=true
app.seed.admin.email=admin@local
app.seed.admin.password=Admin123!
app.seed.operator.email=operator@local
app.seed.operator.password=Operator123!
