spring.application.name=backPayments

app.security.jwt.secret=change-me-please-change-me-please-change-me-please
app.security.jwt.expiration=PT2H

app.seed.enabled=true
app.seed.admin.email=admin@local
app.seed.admin.password=Admin123!
app.seed.operator.email=operator@local
app.seed.operator.password=Operator123!
